
server:
  port: 8030

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8010/eureka/ #eureka服务注册地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CR7357353615/Config/ #git仓库地址
          searchPaths: SpringCloudDemo #搜索路径
#          username: username
#          password: password
  application:
    name: config-server
#management:
#  security:
#    enabled: false

#encrypt.key 对应 git webhooks的secret
#encrypt:
#  key: feng


